//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParking.Mobile.Driver.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartParking.Mobile.Driver.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change phone.
        /// </summary>
        public static string Auth_ChangePhone {
            get {
                return ResourceManager.GetString("Auth_ChangePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug OTP.
        /// </summary>
        public static string Auth_DebugOtpTitle {
            get {
                return ResourceManager.GetString("Auth_DebugOtpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is already associated with your account. An OTP code will be sent to this number..
        /// </summary>
        public static string Auth_KnownPhoneMessage {
            get {
                return ResourceManager.GetString("Auth_KnownPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Auth_Phone {
            get {
                return ResourceManager.GetString("Auth_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a phone number..
        /// </summary>
        public static string Auth_PhoneRequired {
            get {
                return ResourceManager.GetString("Auth_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        public static string Auth_SendCode {
            get {
                return ResourceManager.GetString("Auth_SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number to receive a code.
        /// </summary>
        public static string Auth_Subtitle {
            get {
                return ResourceManager.GetString("Auth_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Auth_Title {
            get {
                return ResourceManager.GetString("Auth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to My Bookings.
        /// </summary>
        public static string Booking_BackToBookings {
            get {
                return ResourceManager.GetString("Booking_BackToBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading booking....
        /// </summary>
        public static string Booking_Loading {
            get {
                return ResourceManager.GetString("Booking_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load this booking..
        /// </summary>
        public static string Booking_NotFoundMessage {
            get {
                return ResourceManager.GetString("Booking_NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking not found.
        /// </summary>
        public static string Booking_NotFoundTitle {
            get {
                return ResourceManager.GetString("Booking_NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment creation failed..
        /// </summary>
        public static string Booking_PaymentCreationFailed {
            get {
                return ResourceManager.GetString("Booking_PaymentCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        public static string Booking_PayNow {
            get {
                return ResourceManager.GetString("Booking_PayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking reference.
        /// </summary>
        public static string Booking_Reference {
            get {
                return ResourceManager.GetString("Booking_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Booking_StatusTitle {
            get {
                return ResourceManager.GetString("Booking_StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track the status of your reservation..
        /// </summary>
        public static string Booking_Subtitle {
            get {
                return ResourceManager.GetString("Booking_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string Booking_Title {
            get {
                return ResourceManager.GetString("Booking_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string BookingStatus_Active {
            get {
                return ResourceManager.GetString("BookingStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string BookingStatus_Cancelled {
            get {
                return ResourceManager.GetString("BookingStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string BookingStatus_Completed {
            get {
                return ResourceManager.GetString("BookingStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string BookingStatus_Confirmed {
            get {
                return ResourceManager.GetString("BookingStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string BookingStatus_Expired {
            get {
                return ResourceManager.GetString("BookingStatus_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending payment.
        /// </summary>
        public static string BookingStatus_PendingPayment {
            get {
                return ResourceManager.GetString("BookingStatus_PendingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string BookingSummary_End {
            get {
                return ResourceManager.GetString("BookingSummary_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        public static string BookingSummary_Expires {
            get {
                return ResourceManager.GetString("BookingSummary_Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string BookingSummary_Price {
            get {
                return ResourceManager.GetString("BookingSummary_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string BookingSummary_Start {
            get {
                return ResourceManager.GetString("BookingSummary_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Summary.
        /// </summary>
        public static string BookingSummary_Title {
            get {
                return ResourceManager.GetString("BookingSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Payment.
        /// </summary>
        public static string MyBookings_ConfirmPayment {
            get {
                return ResourceManager.GetString("MyBookings_ConfirmPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservations will appear here..
        /// </summary>
        public static string MyBookings_EmptyMessage {
            get {
                return ResourceManager.GetString("MyBookings_EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bookings yet.
        /// </summary>
        public static string MyBookings_EmptyTitle {
            get {
                return ResourceManager.GetString("MyBookings_EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string MyBookings_End {
            get {
                return ResourceManager.GetString("MyBookings_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver session is invalid..
        /// </summary>
        public static string MyBookings_InvalidSession {
            get {
                return ResourceManager.GetString("MyBookings_InvalidSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading bookings....
        /// </summary>
        public static string MyBookings_Loading {
            get {
                return ResourceManager.GetString("MyBookings_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string MyBookings_Payment {
            get {
                return ResourceManager.GetString("MyBookings_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        public static string MyBookings_PayNow {
            get {
                return ResourceManager.GetString("MyBookings_PayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string MyBookings_Price {
            get {
                return ResourceManager.GetString("MyBookings_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string MyBookings_Start {
            get {
                return ResourceManager.GetString("MyBookings_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your reservations and continue pending payments..
        /// </summary>
        public static string MyBookings_Subtitle {
            get {
                return ResourceManager.GetString("MyBookings_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bookings.
        /// </summary>
        public static string MyBookings_Title {
            get {
                return ResourceManager.GetString("MyBookings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Booking.
        /// </summary>
        public static string MyBookings_ViewBooking {
            get {
                return ResourceManager.GetString("MyBookings_ViewBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bookings.
        /// </summary>
        public static string Nav_Bookings {
            get {
                return ResourceManager.GetString("Nav_Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Nav_Profile {
            get {
                return ResourceManager.GetString("Nav_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Nav_Search {
            get {
                return ResourceManager.GetString("Nav_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string ParkingCard_Available {
            get {
                return ResourceManager.GetString("ParkingCard_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best option.
        /// </summary>
        public static string ParkingCard_BestOption {
            get {
                return ResourceManager.GetString("ParkingCard_BestOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheapest.
        /// </summary>
        public static string ParkingCard_Cheapest {
            get {
                return ResourceManager.GetString("ParkingCard_Cheapest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string ParkingCard_Distance {
            get {
                return ResourceManager.GetString("ParkingCard_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated.
        /// </summary>
        public static string ParkingCard_Estimated {
            get {
                return ResourceManager.GetString("ParkingCard_Estimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string ParkingCard_Full {
            get {
                return ResourceManager.GetString("ParkingCard_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string ParkingCard_Rate {
            get {
                return ResourceManager.GetString("ParkingCard_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Parking.
        /// </summary>
        public static string ParkingCard_ViewParking {
            get {
                return ResourceManager.GetString("ParkingCard_ViewParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Time.
        /// </summary>
        public static string ParkingDetails_AdjustTime {
            get {
                return ResourceManager.GetString("ParkingDetails_AdjustTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string ParkingDetails_Available {
            get {
                return ResourceManager.GetString("ParkingDetails_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking creation failed..
        /// </summary>
        public static string ParkingDetails_BookingCreationFailed {
            get {
                return ResourceManager.GetString("ParkingDetails_BookingCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string ParkingDetails_End {
            get {
                return ResourceManager.GetString("ParkingDetails_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be greater than start time..
        /// </summary>
        public static string ParkingDetails_EndAfterStart {
            get {
                return ResourceManager.GetString("ParkingDetails_EndAfterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string ParkingDetails_Hours {
            get {
                return ResourceManager.GetString("ParkingDetails_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading parking....
        /// </summary>
        public static string ParkingDetails_Loading {
            get {
                return ResourceManager.GetString("ParkingDetails_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load this parking..
        /// </summary>
        public static string ParkingDetails_NotFoundMessage {
            get {
                return ResourceManager.GetString("ParkingDetails_NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking not found.
        /// </summary>
        public static string ParkingDetails_NotFoundTitle {
            get {
                return ResourceManager.GetString("ParkingDetails_NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string ParkingDetails_QuoteTitle {
            get {
                return ResourceManager.GetString("ParkingDetails_QuoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string ParkingDetails_Rate {
            get {
                return ResourceManager.GetString("ParkingDetails_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Quote.
        /// </summary>
        public static string ParkingDetails_RecalculateQuote {
            get {
                return ResourceManager.GetString("ParkingDetails_RecalculateQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Parking.
        /// </summary>
        public static string ParkingDetails_Reserve {
            get {
                return ResourceManager.GetString("ParkingDetails_Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ParkingDetails_Start {
            get {
                return ResourceManager.GetString("ParkingDetails_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review details and confirm your reservation..
        /// </summary>
        public static string ParkingDetails_Subtitle {
            get {
                return ResourceManager.GetString("ParkingDetails_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking Details.
        /// </summary>
        public static string ParkingDetails_Title {
            get {
                return ResourceManager.GetString("ParkingDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string ParkingDetails_Total {
            get {
                return ResourceManager.GetString("ParkingDetails_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Payment.
        /// </summary>
        public static string Payment_Confirm {
            get {
                return ResourceManager.GetString("Payment_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading payment....
        /// </summary>
        public static string Payment_Loading {
            get {
                return ResourceManager.GetString("Payment_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load this payment..
        /// </summary>
        public static string Payment_NotFoundMessage {
            get {
                return ResourceManager.GetString("Payment_NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment not found.
        /// </summary>
        public static string Payment_NotFoundTitle {
            get {
                return ResourceManager.GetString("Payment_NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your payment to secure your booking..
        /// </summary>
        public static string Payment_Subtitle {
            get {
                return ResourceManager.GetString("Payment_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment_Title {
            get {
                return ResourceManager.GetString("Payment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View My Bookings.
        /// </summary>
        public static string Payment_ViewBookings {
            get {
                return ResourceManager.GetString("Payment_ViewBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string PaymentStatus_Cancelled {
            get {
                return ResourceManager.GetString("PaymentStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string PaymentStatus_Failed {
            get {
                return ResourceManager.GetString("PaymentStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string PaymentStatus_Paid {
            get {
                return ResourceManager.GetString("PaymentStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string PaymentStatus_Pending {
            get {
                return ResourceManager.GetString("PaymentStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string PaymentSummary_Amount {
            get {
                return ResourceManager.GetString("PaymentSummary_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string PaymentSummary_Method {
            get {
                return ResourceManager.GetString("PaymentSummary_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string PaymentSummary_Title {
            get {
                return ResourceManager.GetString("PaymentSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Profile_Account {
            get {
                return ResourceManager.GetString("Profile_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Profile_Actions {
            get {
                return ResourceManager.GetString("Profile_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change phone.
        /// </summary>
        public static string Profile_ChangePhone {
            get {
                return ResourceManager.GetString("Profile_ChangePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Profile_Language {
            get {
                return ResourceManager.GetString("Profile_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Profile_Logout {
            get {
                return ResourceManager.GetString("Profile_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Profile_Name {
            get {
                return ResourceManager.GetString("Profile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Profile_Phone {
            get {
                return ResourceManager.GetString("Profile_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Profile_SelectLanguage {
            get {
                return ResourceManager.GetString("Profile_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver account information..
        /// </summary>
        public static string Profile_Subtitle {
            get {
                return ResourceManager.GetString("Profile_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try adjusting your filters..
        /// </summary>
        public static string Results_AdjustFilters {
            get {
                return ResourceManager.GetString("Results_AdjustFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Results_Distance {
            get {
                return ResourceManager.GetString("Results_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Results_Loading {
            get {
                return ResourceManager.GetString("Results_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string Results_NoResults {
            get {
                return ResourceManager.GetString("Results_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open only.
        /// </summary>
        public static string Results_OpenOnly {
            get {
                return ResourceManager.GetString("Results_OpenOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Results_Price {
            get {
                return ResourceManager.GetString("Results_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the best option for your trip..
        /// </summary>
        public static string Results_Subtitle {
            get {
                return ResourceManager.GetString("Results_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Parking.
        /// </summary>
        public static string Results_Title {
            get {
                return ResourceManager.GetString("Results_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string Search_1Hour {
            get {
                return ResourceManager.GetString("Search_1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 km.
        /// </summary>
        public static string Search_1km {
            get {
                return ResourceManager.GetString("Search_1km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        public static string Search_2Hours {
            get {
                return ResourceManager.GetString("Search_2Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 km.
        /// </summary>
        public static string Search_3km {
            get {
                return ResourceManager.GetString("Search_3km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 hours.
        /// </summary>
        public static string Search_4Hours {
            get {
                return ResourceManager.GetString("Search_4Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 m.
        /// </summary>
        public static string Search_500m {
            get {
                return ResourceManager.GetString("Search_500m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Parking.
        /// </summary>
        public static string Search_Action {
            get {
                return ResourceManager.GetString("Search_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current radius.
        /// </summary>
        public static string Search_CurrentRadius {
            get {
                return ResourceManager.GetString("Search_CurrentRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Search_End {
            get {
                return ResourceManager.GetString("Search_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting location....
        /// </summary>
        public static string Search_GettingLocation {
            get {
                return ResourceManager.GetString("Search_GettingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string Search_Lat {
            get {
                return ResourceManager.GetString("Search_Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lng.
        /// </summary>
        public static string Search_Lng {
            get {
                return ResourceManager.GetString("Search_Lng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Search_Location {
            get {
                return ResourceManager.GetString("Search_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get location..
        /// </summary>
        public static string Search_LocationError {
            get {
                return ResourceManager.GetString("Search_LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Duration.
        /// </summary>
        public static string Search_QuickDuration {
            get {
                return ResourceManager.GetString("Search_QuickDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Radius.
        /// </summary>
        public static string Search_Radius {
            get {
                return ResourceManager.GetString("Search_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Search_Start {
            get {
                return ResourceManager.GetString("Search_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly search nearby parking spots..
        /// </summary>
        public static string Search_Subtitle {
            get {
                return ResourceManager.GetString("Search_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Parking.
        /// </summary>
        public static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my location.
        /// </summary>
        public static string Search_UseMyLocation {
            get {
                return ResourceManager.GetString("Search_UseMyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Status_Closed {
            get {
                return ResourceManager.GetString("Status_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Status_Full {
            get {
                return ResourceManager.GetString("Status_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Status_Open {
            get {
                return ResourceManager.GetString("Status_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VerifyOtp_Action {
            get {
                return ResourceManager.GetString("VerifyOtp_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Code.
        /// </summary>
        public static string VerifyOtp_Code {
            get {
                return ResourceManager.GetString("VerifyOtp_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP code.
        /// </summary>
        public static string VerifyOtp_CodePlaceholder {
            get {
                return ResourceManager.GetString("VerifyOtp_CodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required..
        /// </summary>
        public static string VerifyOtp_CodeRequired {
            get {
                return ResourceManager.GetString("VerifyOtp_CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code returned by the API:.
        /// </summary>
        public static string VerifyOtp_DebugMessage {
            get {
                return ResourceManager.GetString("VerifyOtp_DebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug OTP.
        /// </summary>
        public static string VerifyOtp_DebugTitle {
            get {
                return ResourceManager.GetString("VerifyOtp_DebugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string VerifyOtp_Name {
            get {
                return ResourceManager.GetString("VerifyOtp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string VerifyOtp_NamePlaceholder {
            get {
                return ResourceManager.GetString("VerifyOtp_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string VerifyOtp_Phone {
            get {
                return ResourceManager.GetString("VerifyOtp_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required..
        /// </summary>
        public static string VerifyOtp_PhoneRequired {
            get {
                return ResourceManager.GetString("VerifyOtp_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code you received.
        /// </summary>
        public static string VerifyOtp_Subtitle {
            get {
                return ResourceManager.GetString("VerifyOtp_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string VerifyOtp_Title {
            get {
                return ResourceManager.GetString("VerifyOtp_Title", resourceCulture);
            }
        }
    }
}
