// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartParking.Infrastructure.Persistence;

#nullable disable

namespace SmartParking.Infrastructure.Migrations
{
    [DbContext(typeof(SmartParkingDbContext))]
    partial class SmartParkingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartParking.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("ParkingId")
                        .HasColumnType("uuid")
                        .HasColumnName("parking_id");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("price_currency");

                    b.Property<decimal>("ReservedPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("reserved_price");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_bookings_driver");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_bookings_expiry");

                    b.HasIndex("ParkingId")
                        .HasDatabaseName("ix_bookings_parking");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bookings_status");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("ck_currency_len", "char_length(\"price_currency\") = 3");

                            t.HasCheckConstraint("ck_price_valid", "\"reserved_price\" >= 0");

                            t.HasCheckConstraint("ck_time_valid", "\"end_time_utc\" > \"start_time_utc\"");
                        });
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("operators", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Parking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("AvailableCount")
                        .HasColumnType("integer")
                        .HasColumnName("available_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_parkings_operator");

                    b.HasIndex("Status", "AvailableCount")
                        .HasDatabaseName("ix_parkings_search");

                    b.ToTable("parkings", null, t =>
                        {
                            t.HasCheckConstraint("ck_available_valid", "\"available_count\" >= 0 AND \"available_count\" <= \"total_capacity\"");

                            t.HasCheckConstraint("ck_capacity_positive", "\"total_capacity\" > 0");

                            t.HasCheckConstraint("ck_currency_len", "char_length(\"currency\") = 3");

                            t.HasCheckConstraint("ck_hourly_rate_valid", "\"hourly_rate\" >= 0");
                        });
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<string>("ProviderReference")
                        .HasColumnType("text")
                        .HasColumnName("provider_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_payments_booking");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_payments_status");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_amount_valid", "\"amount\" >= 0");

                            t.HasCheckConstraint("ck_currency_len", "char_length(\"currency\") = 3");
                        });
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartParking.Domain.Entities.Parking", null)
                        .WithMany()
                        .HasForeignKey("ParkingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Parking", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
